### ISSUE TITLE
Every incoming event clears the chat input line

### ISSUE THREAD

**Issue by beorn7** [tobymao/rolling_stock#104]
Which means, if an event comes in while typing, all the typed text is lost and you start over.

**Comment by tobymao** [comment]
Beorn I cannot reproduce this. I tested this locally and with Ben and a green updated banner pops up when someone else does something. Let me know if I'm missing something.

1. Type something on the chat.
2. Someone does something like chat or passes.
3. For me a green banner pops up saying the game was updated but the screen should not refresh.

**Comment by tobymao** [comment]
ok sneaky. your right there was a bug. but only sometimes. if the text box loses focuses it works properly. not if you're actually typing mid sentence. fixed!
