### ISSUE TITLE
Passing during Phase 3

### ISSUE THREAD

**Issue by franczyk** [tobymao/rolling_stock#11]
Attempting to pass during auction does not work for me.

To recreate:

P1 - Create game
P1 - Join as player
P2 - Join as player
P1 - Start game
P1 - Click MHE , Click Make Bid
P2 - Click Make Bid
P1 - Click Pass - 

At this point, no passing occurs.  Player turn does not advance to the other player or to next phase.

**Comment by franczyk** [comment]
This has been resolved in the latest build.

**Comment by tobymao** [comment]
your latest pull request fixes this. i did not see this problem because my ids were all single digits.
