### ISSUE TITLE
Selling a shares sells all shares held

### ISSUE THREAD

**Issue by RobertD67** [tobymao/rolling_stock#128]
Selling a shares sells all shares held, however it only pays the user for one share sold. This just happened to RobSlave in game 358 and it happened to RobertD in a previous game a couple of days ago.

**Comment by tobymao** [comment]
I'm not sure what you mean. When you sell a share you share one at a time. I looked at 358 and i don't see any problems.

**Comment by RobertD67** [comment]
Disregard. I'll have to keep an eye on it. It is now showing that RobSlave has the 1 share left. Not sure if it was a glitch on the Tablet, or if I was somehow seeing things. I'll keep an eye out going forward and if it seems to happen again I grab screenshots.
