### ISSUE TITLE
Auction Options

### ISSUE THREAD

**Issue by scottredracecar** [tobymao/rolling_stock#130]
When bidding, there is currently a single checkbox option: "Max Bid". By checking this box, the site appears to bid the next possible bid and then incrementally bids from there up to the specified maximum. This option is fine as is, but should be labeled: "Make incremental bids up to this maximum".

Another option could be added that makes the specified bid and then passes on any bids higher than that. This option could be called "Max Bid".

**Comment by tobymao** [comment]
funny, i already had almost that exact text in the hoverbox.
