### ISSUE TITLE
email notifications only when it is your turn

### ISSUE THREAD

**Issue by weisswurst** [tobymao/rolling_stock#131]
Could the email notifications be configured so that you only get an email when it is your turn, but not whenever a message is written in the chat?

**Comment by tobymao** [comment]
hm, maybe another option... i'll see what i can do in the next couple of adys

**Comment by tobymao** [comment]
fixed in 403751ab4aae2ce4d5ac89acfbb7c879a873d606

**Comment by weisswurst** [comment]
Thanks!
