### ISSUE TITLE
Second corporation fails to incorporate.

### ISSUE THREAD

**Issue by franczyk** [tobymao/rolling_stock#18]
To recreate, start two player game.  Have each player win one auction for 1 company each.
Then, during Round 2, Phase 2, have one player form a corporation.  (Star, $10) Then attempt to have the second player form a corporation. (Bear, $11)

I, [2016-12-16T20:10:52.141130 #5800]  INFO -- : (0.000305s) EXECUTE smpsp_4 (SELECT "id", "user_id", "version", "users", "deck", "settings", "state", "created_at", "updated_at" FROM "games" WHERE ("id" = $1) LIMIT 1); ["1"]
I, [2016-12-16T20:10:52.141937 #5800]  INFO -- : (0.000284s) SELECT * FROM "users" WHERE ("id" IN (1, 2))
I, [2016-12-16T20:10:52.142434 #5800]  INFO -- : (0.000130s) EXECUTE smpsap_3 (SELECT "id", "game_id", "round", "phase", "turns", "created_at", "updated_at" FROM "actions" WHERE ("actions"."game_id" = $1)); [1]
I, [2016-12-16T20:10:52.143444 #5800]  INFO -- : (0.000228s) SELECT * FROM "sessions" WHERE ("token" = '211130929cff31409429c804127186b2') LIMIT 1
I, [2016-12-16T20:10:52.143981 #5800]  INFO -- : (0.000119s) EXECUTE smpsap_1 (SELECT "id", "name", "password", "email", "created_at", "updated_at" FROM "users" WHERE ("users"."id" = $1) LIMIT 1); [2]
I, [2016-12-16T20:10:52.144601 #5800]  INFO -- : (0.000272s) SELECT * FROM "actions" WHERE (("game_id" = '1') AND ("round" = 2) AND ("phase" = 2)) LIMIT 1
Unexpected error while processing request: undefined method `price' for nil:NilClass
	/Users/gkf42/DEV/rolling_stock/models/game.rb:236:in `block in process_phase_2'
	/Users/gkf42/DEV/rolling_stock/models/game.rb:236:in `each'
	/Users/gkf42/DEV/rolling_stock/models/game.rb:236:in `find'
	/Users/gkf42/DEV/rolling_stock/models/game.rb:236:in `process_phase_2'
	/Users/gkf42/DEV/rolling_stock/models/game.rb:214:in `process_action_data'
	/Users/gkf42/DEV/rolling_stock/rolling_stock.rb:136:in `block (6 levels) in <class:RollingStock>'
	/Users/gkf42/DEV/rolling_stock/rolling_stock.rb:134:in `each'
	/Users/gkf42/DEV/rolling_stock/rolling_stock.rb:134:in `block (5 levels)

**Comment by tobymao** [comment]
fixed
