### ISSUE TITLE
Unable to buy corp shares

### ISSUE THREAD

**Issue by franczyk** [tobymao/rolling_stock#19]
Start a two player game.  Each player wins an auction for a company
Incorporate both companies.
Then, in Round 2, Phase 3, neither player can purchase shares of either corporation.

I, [2016-12-17T08:46:01.653174 #9719]  INFO -- : (0.000272s) EXECUTE smpsp_4 (SELECT "id", "user_id", "version", "users", "deck", "settings", "state", "created_at", "updated_at" FROM "games" WHERE ("id" = $1) LIMIT 1); ["1"]
I, [2016-12-17T08:46:01.653942 #9719]  INFO -- : (0.000306s) SELECT * FROM "users" WHERE ("id" IN (1, 2))
I, [2016-12-17T08:46:01.654382 #9719]  INFO -- : (0.000128s) EXECUTE smpsap_3 (SELECT "id", "game_id", "round", "phase", "turns", "created_at", "updated_at" FROM "actions" WHERE ("actions"."game_id" = $1)); [1]
I, [2016-12-17T08:46:01.655434 #9719]  INFO -- : (0.000271s) SELECT * FROM "sessions" WHERE ("token" = '5fe6df7f54aaadd073cad6fcd0efa059') LIMIT 1
I, [2016-12-17T08:46:01.656032 #9719]  INFO -- : (0.000141s) EXECUTE smpsap_1 (SELECT "id", "name", "password", "email", "created_at", "updated_at" FROM "users" WHERE ("users"."id" = $1) LIMIT 1); [2]
I, [2016-12-17T08:46:01.656556 #9719]  INFO -- : (0.000230s) SELECT * FROM "actions" WHERE (("game_id" = '1') AND ("round" = 2) AND ("phase" = 3)) LIMIT 1
Unexpected error while processing request: undefined method `unowned?' for nil:NilClass
	/Users/gkf42/DEV/rolling_stock/models/corporation.rb:166:in `each'
	/Users/gkf42/DEV/rolling_stock/models/corporation.rb:166:in `find'
	/Users/gkf42/DEV/rolling_stock/models/corporation.rb:166:in `next_share_price'
	/Users/gkf42/DEV/rolling_stock/models/game.rb:442:in `block in check_no_player_purchases'
	/Users/gkf42/DEV/rolling_stock/models/game.rb:442:in `map'
	/Users/gkf42/DEV/rolling_stock/models/game.rb:442:in `check_no_player_purchases'
	/Users/gkf42/DEV/rolling_stock/models/game.rb:173:in `step'

**Comment by franczyk** [comment]
rolling_stock_development=> select * from actions;
 id | game_id | round | phase |                                                                                                                                                  turns                                                                                                                                                  |         created_at         |         updated_at         
----+---------+-------+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------+----------------------------
  1 |       1 |     1 |     3 | [{"price":"5","company":"KME","player":"1","action":"bid"},{"price":"6","company":"KME","player":"2","action":"bid"},{"player":"1","action":"pass"},{"price":"7","company":"BPM","player":"2","action":"bid"},{"price":"8","company":"BPM","player":"1","action":"bid"},{"player":"2","action":"pass"}] | 2016-12-17 13:42:53.757605 | 2016-12-17 13:43:59.500844
  2 |       1 |     1 |     7 | [{"company":"BPM","action":"pass"},{"company":"KME","action":"pass"}]                                                                                                                                                                                                                                   | 2016-12-17 13:44:17.213975 | 2016-12-17 13:44:18.845809
  3 |       1 |     2 |     2 | [{"corporation":"Android","price":"10","company":"BPM"},{"corporation":"Bear","price":"11","company":"KME"}]                                                                                                                                                                                            | 2016-12-17 13:44:31.338355 | 2016-12-17 13:44:34.447127
  4 |       1 |     2 |     3 | [{"player":"2","action":"pass"}]                                                                                                                                                                                                                                                                        | 2016-12-17 13:44:52.330952 | 2016-12-17 13:46:43.745133

**Comment by tobymao** [comment]
fixed.
