### ISSUE TITLE
Game presents action button to multiple players- Round 4 Phase 2

### ISSUE THREAD

**Issue by franczyk** [tobymao/rolling_stock#24]
Both P2 and P3 are shown a "Form Corporation" web form.

Game Log:

Your Turn
-- Round: 4 Phase: 2 (Form Corporations) --
Starbucks issues a share
Starbucks changes share price 16 to 15
Google issues a share
Google changes share price 22 to 20
-- Round: 3 Phase: 10 (Check Game End) --
Starbucks changes share price 15 to 16
Starbucks pays $0 dividends - Gary receives 0 p3 receives 0 p2 receives 0
Google changes share price 20 to 22
Google pays $0 dividends - Gary receives 0 p3 receives 0 p2 receives 0
-- Round: 3 Phase: 9 (Pay Dividends And Adjust Share Prices) --
Foreign Investor collects 8 income
p2 collects 2 income
p3 collects 5 income
Gary collects 3 income
Google collects 3 income
Starbucks collects 3 income
-- Round: 3 Phase: 8 (Collect Income) --
-- Round: 3 Phase: 7 (Close Companies) --
Corporation Starbucks offers 17 for MS
Starbucks buys BSE for 3
-- Round: 3 Phase: 6 (Corporations Buys Companies) --
Foreign Investor buys BY for 13
-- Round: 3 Phase: 5 (Foreign Investor Buys Companies) --
New player order: ["Gary", "p3", "p2"]
-- Round: 3 Phase: 4 (Determine New Player Order) --
p3 buys BD for 12
p3 bids 12 for BD
Gary buys WT for 11
Gary bids 11 for WT
-- Round: 3 Phase: 3 (Auctions And Share Trading) --
p2 forms corporation Google with MS at $20 - 1 shares issued.
-- Round: 3 Phase: 2 (Form Corporations) --
Starbucks issues a share
Starbucks changes share price 16 to 15
-- Round: 2 Phase: 10 (Check Game End) --
Starbucks changes share price 15 to 16
Starbucks changes share price 14 to 15
Starbucks pays $0 dividends - Gary receives 0 p3 receives 0 p2 receives 0
-- Round: 2 Phase: 9 (Pay Dividends And Adjust Share Prices) --
Foreign Investor collects 5 income
p2 collects 5 income
p3 collects 2 income
Gary collects 1 income
Starbucks collects 2 income
-- Round: 2 Phase: 8 (Collect Income) --
-- Round: 2 Phase: 7 (Close Companies) --
-- Round: 2 Phase: 6 (Corporations Buys Companies) --
-- Round: 2 Phase: 5 (Foreign Investor Buys Companies) --
New player order: ["Gary", "p3", "p2"]
-- Round: 2 Phase: 4 (Determine New Player Order) --
p2 buys MS for 17
p2 bids 17 for MS
p3 buys AKE for 6
p3 bids 6 for AKE
-- Round: 2 Phase: 3 (Auctions And Share Trading) --
Gary forms corporation Starbucks with KME at $14 - 1 shares issued.
-- Round: 2 Phase: 2 (Form Corporations) --
-- Round: 1 Phase: 10 (Check Game End) --
-- Round: 1 Phase: 9 (Pay Dividends And Adjust Share Prices) --
Foreign Investor collects 5 income
Gary collects 3 income
p2 collects 2 income
p3 collects 0 income
-- Round: 1 Phase: 8 (Collect Income) --
-- Round: 1 Phase: 7 (Close Companies) --
-- Round: 1 Phase: 6 (Corporations Buys Companies) --
-- Round: 1 Phase: 5 (Foreign Investor Buys Companies) --
New player order: ["p3", "p2", "Gary"]
-- Round: 1 Phase: 4 (Determine New Player Order) --
Gary buys KME for 6
Gary bids 6 for KME
p3 bids 5 for KME
p2 buys BPM for 7
p2 bids 7 for BPM
Gary buys BSE for 2
Gary bids 2 for BSE
-- Round: 1 Phase: 3 (Auctions And Share Trading) --
-- Round: 1 Phase: 2 (Form Corporations) --

**Comment by tobymao** [comment]
1. need to check offers existing before before skipping rounds
2. need to clear out offers after round 6 / clear out offers after a purchase
3. maybe only check offers in round 6 for can_act?
4. change offer text, remove Corporation...

**Comment by tobymao** [comment]
i believe i've fixed this issue
