### ISSUE TITLE
change ui for phase 6

### ISSUE THREAD

**Issue by tobymao** [tobymao/rolling_stock#34]

**Comment by beorn7** [comment]
Random thoughts:

- Easy fix: Add pending money to the value already.
- Display pending money somewhere?
- It would be great to only see the companies to pick from that the currently selected Corporation can afford and legally buy.
- Allow owners of companies to offer them to corporations. (Can be negotiated in chat, but would still be nice.)

**Comment by beorn7** [comment]
Pending cash is #29 ... my bad.

**Comment by tobymao** [comment]
done except for company offer, that's more complicated, i'll make another ticket for it
